### ISSUE TITLE
CWL Generation - Update to Output Parameter

### ISSUE THREAD

**Issue by brianlee731** [unity-sds/unity-data-services#423] opened 2024-09-10 17:16 UTC
The output of stage-in process needs to be 'catalog.json' not 'stage-in-results.json'

Ex: https://github.com/unity-sds/app-pack-generator/blob/main/app_pack_generator/templates/stage_in.cwl#L56 
![Image](https://github.com/user-attachments/assets/b19c6816-1b59-4c92-87dd-dcd7ca6fddef)

**Comment by ngachung** [comment] 2024-12-09 16:49
Duplicate of https://github.com/unity-sds/unity-project-management/issues/200

**Closed by ngachung** 2024-12-09 16:49 UTC
